<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Perceptron on XOR Gates](#Q2)
3. [Multilayer Perceptron](#Q3)
4. [Keras MMP](#Q4)

<a id="Q1"></a>
## 1. Define the following terms:

**Neuron**: The elementary unit in an artificial neural network. The neuron receives one or more inputs and sums them to produce an output (or activation). Usually each input is separately weighted, and the sum is passed through a non-linear function known as an activation function or transfer function. The transfer functions usually have a sigmoid shape, but they may also take the form of other non-linear functions.

**Input Layer**: The layer is composed of artificial input neurons, and brings the initial data into the system for further processing by subsequent layers of artificial neurons. The input layer is the very beginning of the workflow.

**Hidden Layer**: A layer in between the input layer and output layer, where artificial neurons take in a set of weighted inputs and produce an output through an activation function.

**Output Layer**: The purpose of the output layer is to output a vector of values that is in a format that is suitable for the type of problem being addressed. Typically the output value is modified by an "activation function" to transform it into a format that makes sense in the context of that problem.

**Activation**: The function that decides the output of a node given an input or set of inputs, whether a neuron should be activated or not by calculating weighted sum and further adding bias with it.

 **Backpropagation**: A neural network propagates the signal of the input data forward through its parameters towards the moment of decision, and then backpropagates information about the error, in reverse through the network, so that it can alter the parameters. This happens step by step:
- The network makes a guess about data, using its parameters
- The network’s is measured with a loss function
- The error is backpropagated to adjust the wrong-headed parameters


## 2. Perceptron on AND Gates <a id="Q3=2"></a>

Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

|x1	|x2|x3|	y|
|---|---|---|---|
1|	1|	1|	1|
1|	0|	1|	0|
0|	1|	1|	0|
0|	0|	1|	0|

In [1]:
import numpy as np
import pandas as pd

In [2]:
X = np.array([[1,1,1,1],
              [1,0,1,1],
              [0,1,1,1],
              [0,0,1,1]])

y = [[1], [0], [0], [0]]

In [3]:
class NeuralNetwork:
    def __init__(self):
        #set up architecture of NN
        self.input = 4
        self.hiddenNodes = 4
        self.outputNodes = 1
        
        #initial weights
        self.weights1 = np.random.randn(self.input, self.hiddenNodes)
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        '''calculate the NN inference using feed forward'''
        
        #weighted sum of inputs and hidden
        self.hidden_sum = np.dot(X, self.weights1)
            
        #activation of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
          
        #weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        #final activation
        self.activated_output = self.sigmoid(self.output_sum)
            
        return self.activated_output
    
    def backward(self, X, y, o):
        '''backward propagate through the network'''
        self.o_error = y-o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) #apply derivative of sigmoid to error
        
        self.z2_error = self.o_delta.dot(self.weights2.T) #z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta) #adjust first set(input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)


nn = NeuralNetwork()
for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 50 == 0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[1 1 1 1]
 [1 0 1 1]
 [0 1 1 1]
 [0 0 1 1]]
Actual Output: 
 [[1], [0], [0], [0]]
Predicted Output: 
 [[0.33503028]
 [0.34815219]
 [0.27797582]
 [0.28692757]]
Loss: 
 0.1807481662132464
+---------EPOCH 2---------+
Input: 
 [[1 1 1 1]
 [1 0 1 1]
 [0 1 1 1]
 [0 0 1 1]]
Actual Output: 
 [[1], [0], [0], [0]]
Predicted Output: 
 [[0.32227391]
 [0.33334551]
 [0.26480593]
 [0.27196109]]
Loss: 
 0.17862922544310386
+---------EPOCH 3---------+
Input: 
 [[1 1 1 1]
 [1 0 1 1]
 [0 1 1 1]
 [0 0 1 1]]
Actual Output: 
 [[1], [0], [0], [0]]
Predicted Output: 
 [[0.31650915]
 [0.32531401]
 [0.25743784]
 [0.26255774]]
Loss: 
 0.17704993956579507
+---------EPOCH 4---------+
Input: 
 [[1 1 1 1]
 [1 0 1 1]
 [0 1 1 1]
 [0 0 1 1]]
Actual Output: 
 [[1], [0], [0], [0]]
Predicted Output: 
 [[0.31456758]
 [0.32097214]
 [0.25317382]
 [0.25611454]]
Loss: 
 0.17563309198274174
+---------EPOCH 5---------+
Input: 
 [[1 1 1 1]
 [1 0 1 1]
 [0 1 1 1]
 [0 0 1 1]]
Actual Output: 
 [[

In [4]:
output = nn.feed_forward(X).round().astype(int)
output

array([[1],
       [0],
       [0],
       [0]])

In [5]:
output == y

array([[ True],
       [ True],
       [ True],
       [ True]])

## 3. Multilayer Perceptron <a id="Q3"></a>

Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights.
Your network must have one hidden layer.
You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
Train your model on the Heart Disease dataset from UCI:



In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')

In [18]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [19]:
X = df.drop('target', axis=1).values
y = df['target'].values.reshape(-1,1)

X.shape, y.shape

((303, 13), (303, 1))

In [40]:
df['target'].value_counts(normalize=True)

1    0.544554
0    0.455446
Name: target, dtype: float64

In [22]:
class NeuralNetwork:
    def __init__(self):
        #set up architecture of NN
        self.input = 13
        self.hiddenNodes = 16
        self.outputNodes = 1
        
        #initial weights
        self.weights1 = np.random.randn(self.input, self.hiddenNodes)
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        '''calculate the NN inference using feed forward'''
        
        #weighted sum of inputs and hidden
        self.hidden_sum = np.dot(X, self.weights1)
            
        #activation of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
          
        #weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        #final activation
        self.activated_output = self.sigmoid(self.output_sum)
            
        return self.activated_output
    
    def backward(self, X, y, o):
        '''backward propagate through the network'''
        self.o_error = y-o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) #apply derivative of sigmoid to error
        
        self.z2_error = self.o_delta.dot(self.weights2.T) #z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta) #adjust first set(input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)


nn = NeuralNetwork()
for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 50 == 0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
#         print('Input: \n', X)
#         print('Actual Output: \n', y)
#         print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Loss: 
 0.28273578041091113
+---------EPOCH 2---------+
Loss: 
 0.48704804131656954
+---------EPOCH 3---------+
Loss: 
 0.45544554455445546
+---------EPOCH 4---------+
Loss: 
 0.45544554455445546
+---------EPOCH 5---------+
Loss: 
 0.45544554455445546
+---------EPOCH 50---------+
Loss: 
 0.45544554455445546
+---------EPOCH 100---------+
Loss: 
 0.45544554455445546
+---------EPOCH 150---------+
Loss: 
 0.45544554455445546
+---------EPOCH 200---------+
Loss: 
 0.45544554455445546
+---------EPOCH 250---------+
Loss: 
 0.45544554455445546
+---------EPOCH 300---------+
Loss: 
 0.45544554455445546
+---------EPOCH 350---------+
Loss: 
 0.45544554455445546
+---------EPOCH 400---------+
Loss: 
 0.45544554455445546
+---------EPOCH 450---------+
Loss: 
 0.45544554455445546
+---------EPOCH 500---------+
Loss: 
 0.45544554455445546
+---------EPOCH 550---------+
Loss: 
 0.45544554455445546
+---------EPOCH 600---------+
Loss: 
 0.45544554455445546
+---------EPOCH 650------

## 4. Keras MMP <a id="Q4"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. 
- Use the Heart Disease Dataset (binary classification)
- Use an appropriate loss function for a binary classification task
- Use an appropriate activation function on the final layer of your network.
- Train your model and report its baseline accuracy. 
- Train your model using verbose output for ease of grading.


- Then hyperparameter tune at least two parameters and report your model's accuracy.
- Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
- When hyperparameter tuning, show you work by adding code cells for each new experiment.
- Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
- You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [84]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [93]:
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier
np.random.seed(42)

model = Sequential()

#hidden
model.add(Dense(13, input_dim=13, activation='relu'))
model.add(Dropout(.2))

#output
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
                    optimizer='adam', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_116 (Dense)            (None, 13)                182       
_________________________________________________________________
dropout_8 (Dropout)          (None, 13)                0         
_________________________________________________________________
dense_117 (Dense)            (None, 1)                 14        
Total params: 196
Trainable params: 196
Non-trainable params: 0
_________________________________________________________________


In [95]:
results = model.fit(X_train, y_train, batch_size=16, epochs=50, validation_split=.15, verbose=1)
scores = model.evaluate(X_test, y_test)
print(f'Baseline {model.metrics_names[1]}: {scores[1]*100}')

Train on 205 samples, validate on 37 samples
Epoch 1/50
205/205 [==============================] - 0s 200us/step - loss: 6.6516 - acc: 0.5122 - val_loss: 1.8747 - val_acc: 0.7568
Epoch 2/50
205/205 [==============================] - 0s 132us/step - loss: 5.7369 - acc: 0.5561 - val_loss: 2.0235 - val_acc: 0.7027
Epoch 3/50
205/205 [==============================] - 0s 122us/step - loss: 5.7423 - acc: 0.5659 - val_loss: 1.8880 - val_acc: 0.6757
Epoch 4/50
205/205 [==============================] - 0s 122us/step - loss: 5.0676 - acc: 0.5854 - val_loss: 2.2594 - val_acc: 0.6757
Epoch 5/50
205/205 [==============================] - 0s 127us/step - loss: 5.7387 - acc: 0.5512 - val_loss: 1.8095 - val_acc: 0.7568
Epoch 6/50
205/205 [==============================] - 0s 151us/step - loss: 5.7712 - acc: 0.5415 - val_loss: 1.8577 - val_acc: 0.6757
Epoch 7/50
205/205 [==============================] - 0s 127us/step - loss: 5.4312 - acc: 0.5951 - val_loss: 2.1067 - val_acc: 0.7297
Epoch 8/50
205/20

In [106]:
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
np.random.seed(42)

# Function to create model, required for KerasClassifier
def create_model(activation):
	# create model
	model = Sequential()
	model.add(Dense(13, input_dim=13, activation=activation))
	model.add(Dropout(.2))
	model.add(Dense(1, activation='sigmoid'))
    
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=1)

# define the grid search parameters
param_grid = {'activation': ['relu', 'sigmoid'],
              'batch_size': [10, 50, 100],
              'epochs': [100]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=3)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

grid_result.score(X_test, y_test)

Epoch 1/100
161/161 [==============================] - 5s 32ms/step - loss: 7.3780 - acc: 0.5280
Epoch 2/100
161/161 [==============================] - 0s 230us/step - loss: 5.8089 - acc: 0.5839
Epoch 3/100
161/161 [==============================] - 0s 242us/step - loss: 7.4697 - acc: 0.4596
Epoch 4/100
161/161 [==============================] - 0s 255us/step - loss: 5.6204 - acc: 0.5776
Epoch 5/100
161/161 [==============================] - 0s 248us/step - loss: 5.2805 - acc: 0.5714
Epoch 6/100
161/161 [==============================] - 0s 255us/step - loss: 5.4020 - acc: 0.6025
Epoch 7/100
161/161 [==============================] - 0s 242us/step - loss: 6.0310 - acc: 0.5404
Epoch 8/100
161/161 [==============================] - 0s 267us/step - loss: 6.4021 - acc: 0.5217
Epoch 9/100
161/161 [==============================] - 0s 224us/step - loss: 6.1641 - acc: 0.5590
Epoch 10/100
161/161 [==============================] - 0s 255us/step - loss: 6.2873 - acc: 0.5590
Epoch 11/100
161/161

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/100
242/242 [==============================] - 6s 24ms/step - loss: 7.8543 - acc: 0.4876
Epoch 2/100
242/242 [==============================] - 0s 240us/step - loss: 7.8675 - acc: 0.4835
Epoch 3/100
242/242 [==============================] - 0s 244us/step - loss: 8.4855 - acc: 0.4380
Epoch 4/100
242/242 [==============================] - 0s 264us/step - loss: 7.2338 - acc: 0.4876
Epoch 5/100
242/242 [==============================] - 0s 273us/step - loss: 7.2695 - acc: 0.4669
Epoch 6/100
242/242 [==============================] - 0s 269us/step - loss: 6.0864 - acc: 0.5331
Epoch 7/100
242/242 [==============================] - 0s 260us/step - loss: 5.9704 - acc: 0.5496
Epoch 8/100
242/242 [==============================] - 0s 273us/step - loss: 6.4571 - acc: 0.5248
Epoch 9/100
242/242 [==============================] - 0s 269us/step - loss: 6.0324 - acc: 0.5331
Epoch 10/100
242/242 [==============================] - 0s 264us/step - loss: 6.1921 - acc: 0.5455
Epoch 11/100
242/242

0.8196721272390397

In [107]:
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
np.random.seed(42)

# Function to create model, required for KerasClassifier
def create_model(activation):
	# create model
	model = Sequential()
	model.add(Dense(13, input_dim=13, activation=activation))
	model.add(Dropout(.2))
	model.add(Dense(1, activation='sigmoid'))
    
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=1)

# define the grid search parameters
param_grid = {'activation': ['relu'],
              'batch_size': [5,10,15],
              'epochs': [50,100]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=3)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

grid_result.score(X_test, y_test)

Epoch 1/50
161/161 [==============================] - 6s 36ms/step - loss: 6.1579 - acc: 0.5963
Epoch 2/50
161/161 [==============================] - 0s 503us/step - loss: 5.2813 - acc: 0.5590
Epoch 3/50
161/161 [==============================] - 0s 497us/step - loss: 7.0585 - acc: 0.4534
Epoch 4/50
161/161 [==============================] - 0s 491us/step - loss: 5.4223 - acc: 0.6025
Epoch 5/50
161/161 [==============================] - 0s 466us/step - loss: 5.4014 - acc: 0.5528
Epoch 6/50
161/161 [==============================] - 0s 584us/step - loss: 5.4387 - acc: 0.6149
Epoch 7/50
161/161 [==============================] - 0s 491us/step - loss: 6.1600 - acc: 0.5404
Epoch 8/50
161/161 [==============================] - 0s 478us/step - loss: 6.0468 - acc: 0.5839
Epoch 9/50
161/161 [==============================] - 0s 478us/step - loss: 6.4806 - acc: 0.5155
Epoch 10/50
161/161 [==============================] - 0s 485us/step - loss: 5.8321 - acc: 0.5528
Epoch 11/50
161/161 [=========

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/50
242/242 [==============================] - 7s 28ms/step - loss: 7.7591 - acc: 0.4752
Epoch 2/50
242/242 [==============================] - 0s 562us/step - loss: 7.3026 - acc: 0.5289
Epoch 3/50
242/242 [==============================] - 0s 583us/step - loss: 6.8879 - acc: 0.5124
Epoch 4/50
242/242 [==============================] - 0s 599us/step - loss: 7.1751 - acc: 0.5124
Epoch 5/50
242/242 [==============================] - 0s 525us/step - loss: 7.9033 - acc: 0.4711
Epoch 6/50
242/242 [==============================] - 0s 525us/step - loss: 7.7823 - acc: 0.4835
Epoch 7/50
242/242 [==============================] - 0s 525us/step - loss: 7.5948 - acc: 0.4835
Epoch 8/50
242/242 [==============================] - 0s 517us/step - loss: 6.5386 - acc: 0.5248
Epoch 9/50
242/242 [==============================] - 0s 525us/step - loss: 6.0378 - acc: 0.5041
Epoch 10/50
242/242 [==============================] - 0s 686us/step - loss: 5.9050 - acc: 0.5000
Epoch 11/50
242/242 [=========

0.7704918135385044

In [109]:
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
np.random.seed(42)

# Function to create model, required for KerasClassifier
def create_model(activation, dropout):
	# create model
	model = Sequential()
	model.add(Dense(13, input_dim=13, activation=activation))
	model.add(Dropout(dropout))
	model.add(Dense(1, activation='sigmoid'))
    
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=1)

# define the grid search parameters
param_grid = {'activation': ['relu'],
              'batch_size': [10,32,50],
              'dropout': [.1, .15, .2],
              'epochs': [100]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=3)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

grid_result.score(X_test, y_test)

Epoch 1/100
161/161 [==============================] - 7s 43ms/step - loss: 6.7649 - acc: 0.5155
Epoch 2/100
161/161 [==============================] - 0s 267us/step - loss: 4.0987 - acc: 0.6398
Epoch 3/100
161/161 [==============================] - 0s 280us/step - loss: 6.1930 - acc: 0.4845
Epoch 4/100
161/161 [==============================] - 0s 267us/step - loss: 5.5289 - acc: 0.5590
Epoch 5/100
161/161 [==============================] - 0s 267us/step - loss: 5.0793 - acc: 0.5466
Epoch 6/100
161/161 [==============================] - 0s 273us/step - loss: 4.6383 - acc: 0.5901
Epoch 7/100
161/161 [==============================] - 0s 267us/step - loss: 4.9424 - acc: 0.5776
Epoch 8/100
161/161 [==============================] - 0s 267us/step - loss: 4.3582 - acc: 0.6211
Epoch 9/100
161/161 [==============================] - 0s 298us/step - loss: 4.9850 - acc: 0.5714
Epoch 10/100
161/161 [==============================] - 0s 273us/step - loss: 4.7301 - acc: 0.6335
Epoch 11/100
161/161

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/100
242/242 [==============================] - 8s 34ms/step - loss: 7.1807 - acc: 0.5496
Epoch 2/100
242/242 [==============================] - 0s 298us/step - loss: 7.1807 - acc: 0.5496
Epoch 3/100
242/242 [==============================] - 0s 289us/step - loss: 7.1807 - acc: 0.5496
Epoch 4/100
242/242 [==============================] - 0s 298us/step - loss: 7.1807 - acc: 0.5496
Epoch 5/100
242/242 [==============================] - 0s 293us/step - loss: 7.1807 - acc: 0.5496
Epoch 6/100
242/242 [==============================] - 0s 306us/step - loss: 7.1807 - acc: 0.5496
Epoch 7/100
242/242 [==============================] - 0s 335us/step - loss: 7.1807 - acc: 0.5496
Epoch 8/100
242/242 [==============================] - 0s 331us/step - loss: 7.1148 - acc: 0.5537
Epoch 9/100
242/242 [==============================] - 0s 347us/step - loss: 7.1951 - acc: 0.5455
Epoch 10/100
242/242 [==============================] - 0s 343us/step - loss: 7.1807 - acc: 0.5496
Epoch 11/100
242/242

0.5245901717514289

In [110]:
# Function to create model, required for KerasClassifier
def create_model(activation, dropout):
	# create model
	model = Sequential()
	model.add(Dense(13, input_dim=13, activation=activation))
	model.add(Dropout(dropout))
	model.add(Dense(1, activation='sigmoid'))
    
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=1)

# define the grid search parameters
param_grid = {'activation': ['relu'],
              'batch_size': [10],
              'dropout': [.1],
              'epochs': [50, 100, 200]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=3)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

grid_result.score(X_test, y_test)

Epoch 1/50
161/161 [==============================] - 8s 50ms/step - loss: 8.6950 - acc: 0.4472
Epoch 2/50
161/161 [==============================] - 0s 298us/step - loss: 8.0363 - acc: 0.4783
Epoch 3/50
161/161 [==============================] - 0s 292us/step - loss: 8.4839 - acc: 0.4410
Epoch 4/50
161/161 [==============================] - 0s 304us/step - loss: 8.2198 - acc: 0.4845
Epoch 5/50
161/161 [==============================] - 0s 298us/step - loss: 7.9696 - acc: 0.4596
Epoch 6/50
161/161 [==============================] - 0s 311us/step - loss: 7.9122 - acc: 0.4720
Epoch 7/50
161/161 [==============================] - 0s 304us/step - loss: 7.8898 - acc: 0.4969
Epoch 8/50
161/161 [==============================] - 0s 304us/step - loss: 8.6637 - acc: 0.4410
Epoch 9/50
161/161 [==============================] - 0s 304us/step - loss: 8.4695 - acc: 0.4534
Epoch 10/50
161/161 [==============================] - 0s 311us/step - loss: 8.0115 - acc: 0.4845
Epoch 11/50
161/161 [=========

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/200
242/242 [==============================] - 9s 36ms/step - loss: 8.6527 - acc: 0.4628
Epoch 2/200
242/242 [==============================] - 0s 331us/step - loss: 8.4232 - acc: 0.4752
Epoch 3/200
242/242 [==============================] - 0s 360us/step - loss: 9.2023 - acc: 0.4256
Epoch 4/200
242/242 [==============================] - 0s 318us/step - loss: 8.6517 - acc: 0.4587
Epoch 5/200
242/242 [==============================] - 0s 322us/step - loss: 8.6521 - acc: 0.4628
Epoch 6/200
242/242 [==============================] - 0s 318us/step - loss: 8.3160 - acc: 0.4835
Epoch 7/200
242/242 [==============================] - 0s 306us/step - loss: 8.2178 - acc: 0.4876
Epoch 8/200
242/242 [==============================] - 0s 310us/step - loss: 8.9140 - acc: 0.4463
Epoch 9/200
242/242 [==============================] - 0s 306us/step - loss: 8.8821 - acc: 0.4463
Epoch 10/200
242/242 [==============================] - 0s 298us/step - loss: 8.6499 - acc: 0.4504
Epoch 11/200
242/242

0.4754098380198244

In [111]:
# Function to create model, required for KerasClassifier
def create_model(activation, dropout):
	# create model
	model = Sequential()
	model.add(Dense(13, input_dim=13, activation=activation))
	model.add(Dropout(dropout))
	model.add(Dense(1, activation='sigmoid'))
    
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=1)

# define the grid search parameters
param_grid = {'activation': ['relu'],
              'batch_size': [10, 20],
              'dropout': [.1, .2],
              'epochs': [200]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=3)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

grid_result.score(X_test, y_test)

Epoch 1/200
161/161 [==============================] - 9s 54ms/step - loss: 4.2167 - acc: 0.6149
Epoch 2/200
161/161 [==============================] - 0s 323us/step - loss: 4.6326 - acc: 0.5590
Epoch 3/200
161/161 [==============================] - 0s 311us/step - loss: 3.9384 - acc: 0.5901
Epoch 4/200
161/161 [==============================] - 0s 311us/step - loss: 4.9785 - acc: 0.5342
Epoch 5/200
161/161 [==============================] - 0s 304us/step - loss: 4.8919 - acc: 0.5404
Epoch 6/200
161/161 [==============================] - 0s 317us/step - loss: 4.0676 - acc: 0.5466
Epoch 7/200
161/161 [==============================] - 0s 311us/step - loss: 3.7427 - acc: 0.5839
Epoch 8/200
161/161 [==============================] - 0s 317us/step - loss: 4.8890 - acc: 0.5342
Epoch 9/200
161/161 [==============================] - 0s 317us/step - loss: 3.2703 - acc: 0.5776
Epoch 10/200
161/161 [==============================] - 0s 317us/step - loss: 4.7833 - acc: 0.4969
Epoch 11/200
161/161

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/200
242/242 [==============================] - 10s 41ms/step - loss: 7.0692 - acc: 0.5537
Epoch 2/200
242/242 [==============================] - 0s 174us/step - loss: 7.1690 - acc: 0.5496
Epoch 3/200
242/242 [==============================] - 0s 174us/step - loss: 7.1807 - acc: 0.5496
Epoch 4/200
242/242 [==============================] - 0s 174us/step - loss: 7.3139 - acc: 0.5413
Epoch 5/200
242/242 [==============================] - 0s 182us/step - loss: 7.1504 - acc: 0.5496
Epoch 6/200
242/242 [==============================] - 0s 182us/step - loss: 7.1355 - acc: 0.5496
Epoch 7/200
242/242 [==============================] - 0s 182us/step - loss: 6.8724 - acc: 0.5620
Epoch 8/200
242/242 [==============================] - 0s 182us/step - loss: 7.0970 - acc: 0.5455
Epoch 9/200
242/242 [==============================] - 0s 190us/step - loss: 7.0582 - acc: 0.5496
Epoch 10/200
242/242 [==============================] - 0s 182us/step - loss: 6.9060 - acc: 0.5537
Epoch 11/200
242/24

0.7868852537186419